branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: amathon-dev
global:
  application_name: amathon
  branch: null
  default_ec2_keyname: aws
  default_platform: Node.js
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: amathon
  repository: null
  sc: null
  workspace_type: Application
