version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/amathon-eb-circleci
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Install Dependencies && Build Client
          command: |
            cd client
            npm
            npm build